version: "3.9"

services:
  mysql:
    image: mysql:8.4
    container_name: mysql_student
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: mystudent
    ports:
      - "3307:3306"
    volumes:
      - mysqldata:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  mystudent-app:
    build: .
    container_name: mystudent_app
    depends_on:
      mysql:
        condition: service_healthy
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/mystudent
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root

volumes:
  mysqldata: